services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyStrongPassword123!
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data1:/usr/share/opensearch/data

  opensearch-dashboards:   # <-- NEW SERVICE (Dashboard)
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch_dashboards
    ports:
      - "5601:5601"  # OpenSearch Dashboards default port
    depends_on:
      - opensearch-node1
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=MyStrongPassword123!  # Same as OPENSEARCH_INITIAL_ADMIN_PASSWORD

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: searchengine_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - opensearch-node1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/searchdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile-angular
    container_name: searchengine_angular
    ports:
      - "4200:80"

  postgres-db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: searchdb
    volumes:
      - pg_data:/var/lib/postgresql/data

  newman:
    image: postman/newman:alpine  # Use official Newman image
    container_name: searchengine_newman  # Name for the Newman container
    volumes:
      - ./postman-tests:/etc/newman  # Mount your Postman tests directory
    entrypoint: [ "newman", "run", "/etc/newman/collection.json", "-e", "/etc/newman/environment.json" ]  # Entry point for Newman
    depends_on:
      - web  # Wait for the web service to start


volumes:
  opensearch-data1:
  pg_data:
